name: Validate Pull Request
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  checks-pr:
    name: Validate Pull Request
    runs-on: ubuntu-latest
    if: github.actor != 'secured-finance-machine-user[bot]'

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci
        env:
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Format Code
        run: npm run format

      - name: Build Repo
        run: npm run build

      # Skipping test and coverage due to compilation errors in the lending market test
      # Generating the watcher requires cerc-io/graph-ts and cerc-io/graph-cli, but these versions are older than those required in secured-finance-subgraph tests
      # The discrepancy in versions causes the errors
      # TODO: Upgrade cerc-io graph-ts and graph-cli package versions

      # - name: Execute Test
      #   run: npm run test

      # - name: Execute Coverage
      #   run: npm run coverage
